name: Montezuma
favicon: null
layout_spectrum: 0.6586
typography_spectrum: 0.1541815917007625
title: Įrašai apie Įrašus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#32393d'
    - '#354d54'
    - '#6a8cab'
    - '#4b6672'
    - '#020300'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.19953482248820364
  rhythmicContrast: 0.5
purpose: []
